Repository pick-time/pick-time-fe, pull requests merged in 2023-07, with the labels that each got.

#79 Style/modal, giftList 컴포넌트 스타일 수정
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
  src/components/common/ModalFrame.tsx
  src/components/provider/EditGiftModal.tsx
  src/components/provider/ProviderGiftForm.tsx
  src/components/provider/ProviderGiftList.tsx
Labels: style

#82 Feature/coupon UI
  package-lock.json
  package.json
  public/index.html
  src/components/common/CouponList.tsx
  src/components/common/List.tsx
  src/components/common/ModalFrameCoupon.tsx
  src/components/provider/ProviderGiftList.tsx
  src/components/provider/coupon/CreateCouponModal.tsx
  src/components/provider/coupon/CustomButton.tsx
  src/components/provider/coupon/OpenModalButton.tsx
  src/data/couponData.ts
  src/pages/Gift.tsx
  src/stores/couponAtom.ts
  src/style/color.ts
  src/types/couponList.type.ts
Labels: feature, packages, ui

#83 fix: proxy 설정
  src/setupProxy.js
Labels: api

#92 Feature/카카오 공유 버튼 추가
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
  src/components/provider/KakaoShare.tsx
  src/hooks/queries/useGetTargetInfo.tsx
  src/pages/ConsumerResult.tsx
  src/pages/Intro.tsx
  src/pages/ProviderResult.tsx
Labels: feature

#93 선물 목록 불러오기, 선물 삭제 api 연결
  ^
  src/api/provider.ts
  src/components/provider/ProviderGiftForm.tsx
  src/components/provider/ProviderGiftList.tsx
  src/hooks/queries/useGift.ts
  src/hooks/queries/usePostGift.ts
  src/hooks/use.ts
  src/pages/Gift.tsx
Labels: api

#96 Feature/editGiftItem 개별 선물 수정 api
  src/api/provider.ts
  src/components/common/IconLoader.tsx
  src/components/common/ModalFrame.tsx
  src/components/provider/EditGiftModal.tsx
  src/components/provider/ProviderGiftList.tsx
  src/hooks/queries/useGift.ts
  src/setupProxy.js
Labels: api
