Repository pick-time/pick-time-fe, pull requests merged in 2023-10, with the labels that each got.

#103 받는 사람 페이지 미완성 컴포넌트 보강, 랜덤 선택 페이지 추가
  src/App.tsx
  src/api/api.ts
  src/api/consumer.ts
  src/api/provider.ts
  src/components/consumer/ConsumerIntro.tsx
  src/components/provider/CopyLink.tsx
  src/components/provider/ProviderGiftList.tsx
  src/hooks/queries/useGetCardInfo.ts
  src/hooks/queries/useGetTargetInfo.tsx
  src/hooks/queries/usePostTarget.ts
  src/hooks/queries/useResult.ts
  src/hooks/useInputValidation.ts
  src/pages/Confirm.tsx
  src/pages/ConsumerResult.tsx
  src/pages/GiftForConsumer.tsx
  src/pages/RandomSelect.tsx
  src/pages/RecoilSample.tsx
  src/stores/introAtom.ts
  src/types/remote.ts
  src/types/todo.type.ts
  src/utils/randomUtils.ts
Labels: feature

#104 resultType 분리, provider 타입 지정
  src/api/consumer.ts
  src/api/provider.ts
  src/components/provider/ProviderGiftList.tsx
  src/hooks/queries/useResult.ts
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
  src/types/result.type.ts
  src/utils/randomUtils.ts
Labels: api

#106 Fix/provider 씬의 누락된 기능 추가
  src/api/provider.ts
  src/components/common/HeaderWithButton.tsx
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
  src/components/common/List.tsx
  src/components/common/ModalFrameCoupon.tsx
  src/components/provider/ProviderCard.tsx
  src/components/provider/ProviderGiftList.tsx
  src/components/provider/coupon/CreateCouponModal.tsx
  src/components/provider/coupon/OpenModalButton.tsx
  src/data/consumerResultData.ts
  src/data/couponData.ts
  src/data/giftData.ts
  src/hooks/queries/useCoupon.ts
  src/hooks/queries/usePostTarget.ts
  src/pages/Confirm.tsx
  src/pages/Gift.tsx
  src/pages/GiftForConsumer.tsx
Labels: bug, feature, api

#107 Fix/copy link
  src/components/provider/CopyLink.tsx
  src/pages/ProviderResult.tsx
Labels: bug

#109 style: header zindex
  src/components/common/Header.tsx
  src/components/common/HeaderWithButton.tsx
  src/components/provider/ProviderGiftList.tsx
Labels: style
