Repository pick-time/pick-time-fe, pull requests merged in 2023-06, with the labels that each got.

#8 Icon, List 공통 컴포넌트 작업
  .eslintrc.js
  src/App.css
  src/App.tsx
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
  src/components/common/List.tsx
Labels: component

#18 Feature/축하카드 만들기 컴포넌트 생성
  src/components/provider/ProviderCard.tsx
  src/pages/Gift.tsx
Labels: component

#23 Feature/카카오톡 공유하기 기능 구현
  .env.example
  .eslintrc.js
  public/index.html
  src/components/provider/KakaoShare.tsx
Labels: feature

#27 Feature/ Button, Input 컴포넌트 스타일 수정
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/style/color.ts
Labels: style

#28 리스트 페이지 UI completed
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
  src/components/common/List.tsx
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
  src/types/couponList.type.ts
  src/types/giftList.type.ts
Labels: style

#29 Feature/page list
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
Labels: hotfix

#30 Feature/나만의 카드 만들기
  src/App.tsx
  src/pages/Card.tsx
Labels: style

#31 Feature/링크 복사하기 기능 구현
  package-lock.json
  package.json
  src/components/common/Button.tsx
  src/components/provider/CopyLink.tsx
  src/style/GlobalStyle.tsx
Labels: feature

#33 Feature/url 유효성 검사, util 파일 분리
  package-lock.json
  package.json
  server/Router/test.js
  server/server.js
  src/api/api.ts
  src/components/provider/ProviderGiftForm.tsx
  src/components/provider/ProviderGiftList.tsx
  src/utils/urlPattern.ts
  src/utils/validateUrl.ts
Labels: feature

#35 주는 사람 선물 확인 페이지 api
  src/api/api.ts
  src/components/common/List.tsx
  src/pages/Confirm.tsx
  src/types/couponList.type.ts
  src/types/giftList.type.ts
Labels: api

#37 Feature/주는 사람 완성 페이지 퍼블리싱
  src/App.tsx
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
  src/components/provider/CopyLink.tsx
  src/components/provider/KakaoShare.tsx
  src/pages/ProviderResult.tsx
Labels: feature, style

#43 SVG 추가, props case 수정
  src/components/common/Icon.tsx
  src/components/common/IconLoader.tsx
Labels: style

#44 Feature/받는 사람 선물 고른 결과 페이지 퍼블리싱
  src/App.css
  src/App.tsx
  src/components/common/IconLoader.tsx
  src/components/provider/CopyLink.tsx
  src/pages/ConsumerResult.tsx
  src/pages/ProviderResult.tsx
Labels: style

#47 Feature/받는 사람 선물 고른 페이지 API
  src/api/consumerResult.ts
  src/hooks/queries/useGetTargetInfo.tsx
  src/pages/ConsumerResult.tsx
  src/types/remote.ts
Labels: feature

#52 Featrure/선물 고른 페이지 최종 API 연결
  src/api/consumerResult.ts
  src/pages/ConsumerResult.tsx
Labels: feature

#54 Feature/consumer list api
  src/api/api.ts
  src/components/common/Header.tsx
  src/components/common/List.tsx
  src/components/common/Loading.tsx
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
Labels: ui, style

#57 Feature/api error check
  src/api/api.ts
  src/components/common/List.tsx
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
Labels: bug, api

#60 Feature/받는 사람 인트로 API 작업
  src/api/consumer.ts
  src/api/consumerResult.ts
  src/components/common/Image.tsx
  src/components/consumer/ConsumerIntro.tsx
  src/hooks/queries/useGetCardInfo.tsx
  src/hooks/queries/useGetTargetInfo.tsx
  src/types/remote.ts
Labels: feature

#61 Feature/api error check
  src/api/api.ts
  src/components/common/List.tsx
  src/pages/ProviderResult.tsx
  src/setupProxy.js
Labels: bug, api

#64 Feature/모달창 스타일링 수정, url 에러메시지 추가
  server/Router/test.js
  server/server.js
  src/api/api.ts
  src/components/common/ModalFrame.tsx
  src/components/provider/ProviderGiftForm.tsx
  src/components/provider/ProviderGiftList.tsx
  src/utils/validateUrl.ts
Labels: refactor

#66 fix: List 관련 mock data 추가
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
Labels: api

#69 Feature/style list
  src/pages/Confirm.tsx
  src/pages/GiftForConsumer.tsx
Labels: style
